describe('myfirsttest',()=>{
  it('verify positive-visit', () => {
      cy.visit("https://www.amazon.in")
    cy.get('#nav-link-accountList-nav-line-1').click()
    cy.get('#ap_email').click().type('phone number')
    cy.get('.a-button-inner > #continue').click()
    cy.get('#ap_password').click().type('password') 
    cy.get('.a-button-inner > #continue').click()
    cy.get('#cvf-input-code').click().type('OTP')
    cy.get('.a-button-inner > #continue').click()
    cy.get('#ap_password').click().type('password')
    cy.get('#signInSubmit').click()
    cy.wait(5000)
    cy.get('#twotabsearchtextbox').click().type('nike shoes of size 9')
    cy.get('#nav-search-submit-button').click()
    cy.get('[data-asin="B08BW4WF7C"] > .sg-col-inner > .s-widget-container > .s-card-container > .a-spacing-base > .s-product-image-container > .s-image-padding > .rush-component > .a-link-normal > .a-section > .s-image').click()
    cy.get('add-to-cart-button').click()
    cy.get('proceed-to-check-out-action').click()
   })
  })
  